
import re
from typing import List

hm3dsem_cat = [
"void",
"wall",
"picture",
"ceiling",
"pillow",
"door",
"lamp",
"door frame",
"floor",
"window",
"cabinet",
"ceiling lamp",
"box",
"book",
"chair",
"window frame",
"decoration",
"shelf",
"table",
"mirror",
"curtain",
"kitchen cabinet",
"towel",
"painting",
"bag",
"shoe",
"plant",
"clothes",
"sink",
"stairs",
"bed",
"toy",
"tap",
"cardboard box",
"rug",
"toilet",
"beam",
"basket",
"armchair",
"wall lamp",
"drawer",
"shower wall",
"pipe",
"wardrobe",
"wall hanging decoration",
"vase",
"toilet paper",
"cushion",
"bottle",
"tv",
"carpet",
"desk",
"decorative plant",
"radiator",
"door knob",
"ventilation",
"blanket",
"hanger",
"blinds",
"couch",
"photo",
"clutter",
"stool",
"trashcan",
"container",
"window curtain",
"appliance",
"ornament",
"flowerpot",
"product",
"candle",
"device",
"storage box",
"rack",
"nightstand",
"dining chair",
"light fixture",
"support beam",
"basket of something",
"curtain rod",
"towel bar",
"vent",
"bathroom cabinet",
"plate",
"speaker",
"heater",
"window glass",
"kitchen appliance",
"bathroom accessory",
"faucet",
"kitchen lower cabinet",
"clock",
"flower vase",
"board",
"hanging clothes",
"cabinet door",
"cup",
"table lamp",
"dresser",
"air vent",
"case",
"cloth",
"bathtub",
"bin",
"flower",
"refrigerator",
"can",
"bowl",
"cosmetics",
"ceiling vent",
"pot",
"jar",
"glass",
"microwave",
"chest of drawers",
"coffee table",
"bottle of detergent",
"stack of papers",
"bathroom utensil",
"sofa",
"fire alarm",
"fan",
"monitor",
"bucket",
"kitchen counter",
"tray",
"ceiling fan",
"shelving",
"telephone",
"toilet brush",
"kitchen utensil",
"washbasin",
"shower floor",
"bedside lamp",
"pillar",
"mat",
"washing machine",
"alarm",
"dishwasher",
"sensor",
"photo mount",
"oven",
"frame",
"plush toy",
"smoke detector",
"fireplace",
"bench",
"cosmetic",
"wall electronics",
"art frame",
"side table",
"paper",
"kitchen countertop item",
"coffee machine",
"sink cabinet",
"countertop",
"wall panel",
"sign",
"liquid soap",
"toilet paper dispenser",
"paper towel",
"soap dispenser",
"parapet",
"magazine",
"bookshelf",
"hat",
"shower cabin",
"tissue box",
"stairs railing",
"shower curtain",
"chandelier",
"bed table",
"handrail",
"keyboard",
"printer",
"doorpost",
"stair step",
"tool",
"ceiling light",
"stand",
"floor lamp",
"window shutter",
"doormat",
"window shade",
"curtain rail",
"ventilation hood",
"bathroom towel",
"decor",
"stove",
"bath wall",
"chest",
"railing",
"door window",
"pouffe",
"wall clock",
"picture frame",
"shampoo",
"air conditioner",
"clothes hanger",
"ceiling wall",
"showerhead",
"stuffed animal",
"mirror frame",
"electric box",
"step",
"floor mat",
"banister",
"wall board",
"shower dial",
"remote control",
"display cabinet",
"bathroom shelf",
"laundry basket",
"sofa chair",
"wash cabinet",
"decorative plate",
"bar chair",
"partition",
"desk chair",
"folder",
"vacuum cleaner",
"broom",
"laptop",
"trash can",
"ladder",
"brochure",
"storage bin",
"tool box",
"oven and stove",
"boxes",
"kettle",
"seat",
"shelf with clutter",
"sculpture",
"soap",
"strings",
"binder",
"ceiling lower",
"display",
"dining table",
"ceiling light fixture connection",
"office chair",
"statue",
"closet door",
"staircase handrail",
"cabinet /otherroom",
"wall cabinet",
"tv stand",
"closet",
"box with books",
"bar",
"fireplace wall",
"bath towel",
"washing stuff",
"guitar",
"magazines",
"toaster",
"fire extinguisher",
"candle holder",
"fridge",
"light",
"poster",
"machine",
"soap bottle",
"calendar",
"cutting board",
"stack of books",
"price tag",
"gym equipment",
"kitchen island",
"shower knob",
"laundry machine",
"kitchen decoration",
"jewelry",
"artwork",
"ball",
"cuddly toy",
"bowl of fruit",
"kitchen shelf",
"bathroom counter",
"knife holder",
"bottles",
"pad",
"throw blanket",
"radio",
"ceiling molding",
"column",
"shade",
"pile of magazines",
"document",
"newspaper",
"bottle of soap",
"shower tap",
"brush",
"food",
"book rack",
"shower hose/head",
"computer mouse",
"electrical controller",
"jacket",
"amplifier",
"figure",
"door hinge",
"backpack",
"paneling",
"book display",
"can of paint",
"led tv",
"shower door frame",
"alarm clock",
"arch",
"shower",
"range hood",
"bedside cabinet",
"umbrella",
"balustrade",
"kitchen top",
"computer",
"bath sink",
"sliding door",
"sunbed",
"rafter",
"box of tissues",
"shower hose",
"wood",
"handbag",
"cabinet drawer",
"shower bar",
"mouse",
"wall sign",
"handle",
"ironing board",
"bath faucet",
"ceiling under stairs",
"switch",
"board game",
"shower soap shelf",
"storage cabinet",
"teapot",
"garage door",
"exercise equipment",
"camera",
"dumbbell",
"table cloth",
"electric guitar",
"crate",
"vessel",
"ottoman",
"casket",
"desk lamp",
"shower ceiling",
"roof",
"attic door",
"folding chair",
"bath cabinet",
"clothes dryer",
"ceiling pipe",
"luggage",
"scale",
"bath",
"boiler",
"garage door railing",
"bath mat",
"curtain bar",
"bouquet",
"notes",
"shutter",
"air conditioning",
"kitchen countertop items",
"wall tv",
"cooker",
"stack of clothes",
"note",
"ledge",
"snack",
"toilet brush holder",
"globe",
"bedside table",
"kitchen wall",
"bicycle",
"furnace",
"clothes rack",
"candlestick",
"shower rail",
"hose",
"kitchen cabinet lower",
"sofa seat",
"patio chair",
"sliding glass door",
"trophy",
"knob",
"furniture",
"washer-dryer",
"screen",
"shower handle",
"rail",
"worktop",
"electrical box",
"door cabinet",
"lampshade",
"drum",
"stovetop",
"computer desk",
"coffee mug",
"coffee maker",
"wall toilet paper",
"porcelain",
"thermostat",
"object",
"products",
"smoke alarm",
"soap dish",
"piano",
"fire detector",
"bathrobe",
"cover",
"stationery",
"dvd",
"sheet",
"duct",
"kitchen extractor",
"platform",
"l-shaped sofa",
"footrest",
"stack of towels",
"doorstep",
"bath utensil",
"bidet",
"light switch",
"shower shelf",
"pen",
"hunting trophy",
"refrigerator cabinet",
"flower stand",
"bed stand",
"plate of food",
"window shutters",
"exercise ball",
"knife",
"exercise machine",
"papers",
"utensil",
"clothes hanger rod",
"shoe case",
"shower bench",
"panel",
"kitchen cabinet door",
"doll",
"decorative bowl",
"mug",
"bathtub utensil",
"stair",
"recycle bin",
"ceiling door",
"rocking chair",
"flatware",
"exhibition window frame",
"exhibition window",
"shovel",
"fruit",
"lamp table",
"socket",
"desk clutter",
"firewood",
"recessed wall",
"staircase trim",
"shower curtain rod",
"shower tub",
"dustbin",
"exit sign",
"keys",
"jug",
"closet rod",
"wall hanger",
"surface",
"mop",
"dish",
"wine bottle",
"spice rack",
"computer equipment",
"sconce",
"cap",
"fire sprinkler",
"bags",
"mascot",
"holy cross",
"tank",
"towel ring",
"product box",
"containers",
"lace doily",
"cart",
"ceiling window",
"ceiling dome",
"closet shelf",
"storage shelving",
"hook",
"jewelry box",
"washing powder",
"tv remote",
"stone support structure",
"fan coil",
"mini fridge",
"diploma",
"door/window",
"fence",
"locker",
"end table",
"shower caddy",
"bed comforter",
"robe",
"air duct",
"tiles",
"cardboard",
"crib",
"door stopper",
"perfume",
"box of tissue",
"shower door",
"ceiling duct",
"stair wall",
"bathtub platform",
"washbasin counter",
"toothbrush",
"stick",
"fuse box",
"paper storage",
"bedframe",
"lounge chair",
"flag",
"floor vent",
"dog bed",
"archway",
"place mat",
"security camera",
"kitchen table",
"closet mirror wall",
"hand soap",
"shower-bath cabinet",
"hot water/cold water knob",
"fluorescent light",
"wall /outside",
"figurine",
"countertop item",
"rope",
"wine rack",
"motion detector",
"shower rod",
"clothes hamper",
"wall control",
"fruit bowl",
"small table/stand",
"decorative dinnerware",
"doorway",
"kitchen cabinet drawer",
"dishrag",
"record player",
"plunger",
"door/window frame",
"weight",
"shower wall cubby",
"clothes bag",
"coat hanger",
"electric outlet",
"iron",
"outlet",
"identifier",
"shutters",
"media console",
"heater piping",
"ceiling fan lamp",
"shirt",
"door handle",
"fireplace utensil",
"fireplace tool set",
"whiteboard",
"acoustic panel",
"sideboard",
"control panel",
"bathroom wall",
"garage door frame",
"coat",
"sprinkler",
"beanbag",
"ceiling/west wall",
"hearth",
"boxes with books",
"ceiling arch",
"elevator",
"music player",
"trash bag",
"lamp stand",
"rod",
"clothes container",
"plates",
"bar cabinet",
"coat rack",
"file cabinet",
"pc tower",
"cables",
"basin",
"window /outside",
"backrest",
"chest drawer",
"audio cables",
"recessed cubby",
"separator",
"button",
"paper towel dispenser",
"high shelf",
"treadmill",
"wreath",
"wall soap shelf",
"toilet cleaner",
"washing machine and dryer",
"alarm control",
"glasses",
"painting frame",
"exercise bike",
"detergent",
"shower valve",
"briefcase",
"bathroom art",
"tissue",
"counter",
"wall top",
"dinnerware",
"watch",
"plumbing",
"iron board",
"storage",
"mixer",
"dinner chair",
"shower seat",
"oil lamp",
"wheel",
"molding",
"grill",
"cabinet clutter",
"shower pipe",
"decoder",
"garage light",
"garage door opener motor",
"tablet",
"cloth hanger",
"bulletin board",
"canister",
"tire",
"shoe rack",
"toiletry",
"headphones",
"niche",
"lounger",
"shelf cubby",
"cabinet table",
"display table",
"piano stool",
"pool stick",
"violin",
"lighting fixture",
"drawing",
"bottles of wine",
"bath tub",
"bedroom ceiling",
"firewood holder",
"tile",
"lid",
"canvas",
"pan",
"balcony railing",
"carpet roll",
"sewing machine",
"shower curtain bar",
"table pad",
"map",
"pool table",
"dinner table",
"bed sheet",
"binders",
"attic hatch",
"pitcher",
"dressing table",
"computer chair",
"dishes",
"arcade game",
"highchair",
"shower battery",
"baseboard",
"notebook",
"footstool",
"basket of towels",
"fork",
"blankets",
"statue/art",
"shades",
"countertop /otherroom",
"gift",
"kitchen chair",
"sheets / clothes",
"dried flowers",
"mirror door",
"art/muscle shell",
"calculator",
"keyboard piano",
"washcloth",
"box of something",
"floor /outside",
"antique clock",
"stack of cds",
"slippers",
"yoga mat",
"sink pipe",
"dartboard",
"shower tray",
"step stool",
"urinal",
"control",
"projector",
"closet shelving",
"sitting bench",
"island",
"massage bed",
"spa bench",
"freezer",
"shower glass",
"water dispenser",
"headboard",
"ceiling border",
"shower stall",
"shower cockpit",
"albums",
"ukulele",
"mantle",
"cutlery",
"hand towel",
"shelf / cabinet",
"drawers",
"stack of plates",
"wall shelf",
"napkin",
"car",
"table stand",
"shower mat",
"electric wire casing",
"cups",
"ceiling lamp hanger",
"shelf clutter",
"purse",
"closet area for hanging clothes",
"scarf",
"bath dial",
"safe",
"saw",
"pet bed",
"wall indent",
"holder",
"exhibition panel",
"counter door",
"watering can",
"easel",
"chimney",
"laundry bag",
"entertainment set",
"bed curtain",
"phone",
"shop shelf",
"plug",
"patio floor",
"newspaper basket",
"cross",
"silicone tube",
"shisha",
"ceiling support",
"star",
"circular sofa",
"portrait",
"office table",
"hair dryer",
"cleaning clutter",
"piano bench",
"plank",
"shelf with art",
"bathroom rug",
"bathroom floor",
"tree",
"garage door motor",
"stair handle",
"tree branch",
"barrel",
"easy chair",
"stone",
"spoon",
"air freshener",
"sofa set",
"trinket",
"broomstick",
"landing",
"fireplace sconce",
"stack of chairs",
"music equipment stand",
"clarinet",
"product boxes",
"audio cable",
"guitar straps",
"decorative lamp",
"art/clutter",
"drywall board",
"stack of magazines",
"wall detail",
"exercise mat",
"dehumidifier",
"groceries",
"sauna bowl",
"elevator door",
"curtain rod cover",
"dirt ground",
"food tray",
"elephant sculpture",
"set of hangers",
"bed cabinet",
"file",
"pavement",
"workout bike",
"exercise mat roll",
"hair brush",
"beanbag chair",
"wall cubby",
"boots",
"hammock",
"electronics",
"bean bag chair",
"flush button",
"decorative quilt",
"weight bench",
"grass",
"floor stand",
"blackboard",
"brochures",
"flush",
"water tank",
"support",
"bath shelf",
"shower step",
"decorative vase",
"kitchen handle",
"podium",
"pet bowl",
"relief",
"hand dryer",
"sauna support",
"surfboard",
"water heater",
"garden chair",
"stacked chair",
"garage door opener bar",
"dustpan",
"bedpost",
"globe stand",
"pen cup",
"document holder",
"bedside cabinet door",
"trolley",
"wall statue",
"shower frame",
"staircase",
"sauna heater",
"wall beam",
"hammer",
"wine cabinet",
"panel screen",
"unknown/remove",
"ceiling fixture",
"stand/small table",
"stonework",
"cassette",
"laundry",
"stained glass",
"magic marker",
"cleaning liquid",
"extension cord",
"fireplace floor",
"knife set",
"bed small",
"closet storage area",
"coach",
"gloves",
"shade rail",
"scoop",
"kitchenware",
"leaflets",
"shower base",
"window/door",
"gate",
"menu board",
"menu",
"ceramics",
"bathroom window",
"typewriter",
"air vent installation",
"cable",
"book cabinet",
"board games",
"ceiling boarder",
"condiment",
"objects",
"bath towels",
"kitchen counter item",
"bathroom utensils",
"gutter",
"rocking horse",
"bed light",
"soapbox",
"canopy",
"mortar",
"stack of shoes",
"aquarium",
"post",
"rock",
"foosball game table",
"cabinet /w clutter",
"soap dish cubby",
"curtain valence",
"plant ornament",
"set of armchairs",
"cradle",
"hatch",
"bureau",
"mannequin",
"game",
"electricity box",
"tool rack",
"rack of weights",
"telescope",
"napkins",
"oven vent",
"fire screen",
"air refresher",
"folded chair",
"speaker stand",
"bath tap",
"cage",
"baby changing station",
"paper towels",
"shelf with cosmetics",
"electric installation",
"solarium",
"lawn",
"window /otherroom",
"garage door opener",
"bar soap",
"copier machine",
"stapler",
"bedside cabinet drawer",
"cornice",
"cat",
"exhaust pipe",
"sponge",
"artwork frame",
"swing",
"dvd player",
"guitar cases",
"stack of product boxes",
"saxophone",
"album",
"socks",
"schedule",
"electric kettle",
"skylight",
"storage space",
"fireplace shelf",
"puppet",
"wall post",
"grate",
"mantel",
"stairs trim",
"boards",
"roll",
"wifi router",
"boat model",
"chess",
"football",
"wine",
"gym stepper",
"gym mat",
"punchbag",
"cash register",
"display of pictures",
"sandals",
"stage",
"curb",
"keg",
"dish dryer",
"decorative vessel",
"mascots",
"guitar stand",
"moose head/sculpture/hunting trophy",
"electric toothbrush",
"christmas tree",
"wire",
"cans of paint",
"information",
"electric device",
"fishing pole",
"controller",
"pliers",
"screwdriver",
"bathroom glass",
"shoes",
"rake",
"basket with clothes",
"display case",
"vessel sink",
"electric wire",
"electric heater",
"barbecue",
"cabinet kitchen",
"stack of blankets",
"duvet",
"detergent bottle",
"paper holder",
"bathmat",
"computer tower",
"axe",
"plane",
"deck chair",
"weights",
"cleaning fluid",
"pump",
"shower cabinet",
"drill",
"banner",
"liquid cleaner",
"electric cord",
"bricks",
"router",
"recuperator",
"plenum box",
"water pump",
"beer crate",
"medal",
"bottom of stairs",
"fire pit",
"balcony",
"bath door frame",
"rolled carpet",
"vanity",
"paper towel holder",
"medical lamp",
"thermometer",
"sauna seat",
"beverage dispenser",
"electric hub",
"dispenser",
"backsplash",
"salt and pepper",
"fish tank",
"gap",
"bread bin",
"soundbar",
"chaise longue",
"glass door",
"sky",
"cat bed",
"junk",
"jacuzzi",
"bedding",
"pool",
"ashtray",
"kitchen sink",
"bathroom cabinet drawer",
"bathroom cabinet door",
"stereo",
"recessed shelving",
"candelabra",
"billiard cues",
"ball pouffe",
"shower utensil",
"leg rest",
"round chair",
"dress",
"art/statue",
"skateboard",
"clothing stand",
"stack of files",
"drinking fountain",
"cone",
"sticker book",
"electric percussion",
"magic marker box",
"guitar pedals",
"guitar case",
"stack of boxes",
"guitar case cover",
"keyboard stand",
"trombone",
"trumpet",
"material",
"note board",
"bath curtain",
"storage unit",
"cabinet /w cluttered art",
"photos",
"antique telephone",
"ceiling under staircase",
"belt",
"roomba",
"plastic bag",
"fume cupboard",
"stairs wall",
"electric cable",
"baseball cap",
"charger",
"compressor",
"sleeping bag",
"coaster",
"console pad",
"console",
"toiletry bag",
"stereo set",
"set of towels",
"hutch",
"icebox",
"stack",
"barbell",
"payment terminal",
"power strip",
"toothpaste",
"cd player",
"jars",
"receipt printer",
"saturator",
"spices",
"hand cloth",
"aisle frame",
"kitchen utensils",
"shoe shelf",
"eyeglasses",
"dog leash",
"toilet seat",
"decorative lantern",
"curtain hanger",
"stack of stuff",
"installation",
"garage door opener railing",
"baseball bat",
"shoes on shelf",
"rack with shoes",
"bust",
"chassis",
"exhibition picture",
"ice maker",
"cook book",
"bell",
"bathroom mat",
"fur",
"blouse",
"ragdoll",
"doily",
"electrical switchboard",
"measuring tape",
"bookstand",
"baby changing table",
"bathroom stuff",
"slab",
"pedestal",
"liquid",
"water basin",
"wheelbarrow",
"lawn mower",
"ski",
"cabinet mirror",
"cleaning paste",
"lower cabinet",
"cloth dryer",
"flowerbed",
"kitchen counter support",
"power breaker box",
"ceiling bedroom",
"door screen",
"subwoofer",
"stack of pillows",
"stack of bags",
"set of cosmetics",
"central heating furnace",
"set of valves",
"bed cabinet lamp",
"cross-trainer",
"modem",
"cat food",
"chair /w clutter",
"motorcycle",
"dish rack",
"tent",
"headset",
"round cushion",
"tripod",
"baby chair",
"shoes rack",
"sauna",
"music equipment",
"security detector",
"mail",
"ceiling panel",
"ceiling lamp rail",
"medical object",
"meter",
"electrical installation",
"pole",
"extension lead",
"playpen",
"chain",
"wall outside",
"office wall",
"drawer sink table",
"wall panel frame",
"bowl of fruits",
"hole puncher",
"stools",
"mousepad",
"screw box",
"water meter",
"gauge",
"gas meter",
"water outlet",
"crutches",
"bread box",
"electric plug",
"air purifier",
"bicycle helmet",
"sled",
"cleaner",
"cases",
"grab bar",
"shower door knob",
"cleaning paper",
"bath floor",
"golf sticks",
"medal collection",
"kitchen knife set",
"bowl with sweets",
"screen frame",
"box with toys",
"birdhouse",
"box with shoes",
"mirror /otherroom",
"makeup accessories",
"double armchair",
"art piece",
"foot spa",
"spa armchair",
"spa bathtub",
"sauna oven",
"foam",
"box with tea",
"advertisement",
"steel plate",
"flush push",
"cleaner brush",
"solarium door",
"bottle dispenser",
"stairwell",
"flashlight",
"rag",
"chaise",
"alarm controller",
"game board",
"lantern",
"glass pane",
"basin faucet",
"garden bench",
"garden deck",
"gas box",
"soft chair",
"water fountain",
"riser",
"swivel chair",
"pencil",
"sticky notes",
"desk organizer",
"conference phone",
"bath carpet",
"curtain box",
"overhang",
"drainpipe",
"patio",
"tea set",
"billiard balls",
"press",
"pencil holder",
"title",
"toaster oven",
"row of theater chairs",
"rice cooker",
"blanket basket",
"scanner",
"fireplace mirror",
"violin case",
"folding stand",
"partial",
"cat tree",
"stack of yarns",
"den",
"torch",
"trough",
"basket of fruits",
"shower mirror",
"shower window frame",
"ceiling chassis",
"ceiling hanger",
"keyboard cover",
"board with keys",
"tambourine",
"electric drum",
"cabinet counter",
"counter desk",
"stack of albums",
"microphone accessory",
"t-shirt",
"stack of t-shirts",
"keyboard box",
"stack of music stands",
"magazine rack",
"shelf with shoes",
"kitchen lower shelf",
"sewing set",
"sewing tools",
"cd",
"cat litter box",
"shower hanger",
"ceiling corridor",
"cleaning spray",
"salt and pepper grinder",
"ping pong table",
"draw",
"music album shelf",
"powder soap",
"shower grab bar",
"candle stand",
"car model",
"guitar frame",
"ship toy",
"platter",
"decorative bottle",
"audio player",
"firewood chest",
"kitchen seating",
"hats",
"cat toilet",
"fuse panel",
"workstation",
"ceiling floor",
"drawers for clothes",
"sink table",
"extractor hood",
"brushes",
"vegetables",
"waffle iron",
"bag with sheets",
"three",
"stair frame",
"stairs skirt",
"firebox",
"box of fruit",
"fireplace brush",
"pantry",
"shower case",
"drawer desk",
"bread",
"lamp shade",
"soap dispenser shelf in shower",
"crayon",
"drawer cart",
"gas furnace",
"canal",
"cat food bag",
"buckets",
"spirit level",
"air heater",
"trampoline",
"folded table",
"hoverboard",
"kitchen towel",
"knife stand",
"food processor",
"bottle of wine",
"frying pan",
"cooker hood",
"ball chair",
"strongbox",
"dog toy",
"console pad charger",
"gramophone",
"hourglass",
"umbrella stand",
"copier",
"tennis racket",
"bathtub knob",
"glass container",
"stack of trays",
"dish cabinet",
"gym rope",
"meshwork",
"boxing ring",
"emergency sign",
"bed base",
"package",
"cyp",
"stack of binders",
"planner",
"box of paper",
"alcohol bottles",
"cookies",
"bag with something",
"set of knives",
"mobile",
"bridge",
"ball pool",
"mailbox",
"exercise ladder",
"stones",
"sauna heat rocks",
"antlers",
"cleaner bottle",
"sombrero",
"gas container",
"receipt spike",
"spray can",
"bowls",
"bottle opener",
"bunk bed",
"sink/basin",
"baby seat",
"cork board",
"chest of drawer",
"secretary",
"air hockey",
"box with jewelry",
"decorative tray",
"prop",
"fishing rod",
"fitness ball",
"exercising blocks",
"foosball table",
"night lamp",
"skirting board",
"stone bench",
"bath curtain bar",
"bath grab bar",
"attic entrance",
"breadbox",
"photo stand",
"records",
"microphone",
"shoe cabinet",
"sheet music",
"pitchfork",
"salver",
"apron",
"sledge",
"chamber pot",
"floor /otherroom",
"door /otherroom",
"painting /otherroom",
"window frame /otherroom",
"cloth holder",
"foot stand",
"closet floor",
"stack of books / papers",
"decorative cloth",
"wine storage",
"cleaning sponge",
"stack of pots",
"air vent fan",
"shower handrail",
"ceiling fire detector",
"ceiling fan vent",
"bath bar",
"desk cabinet",
"fan air vent",
"pendant",
"box pen",
"bathtub tap",
"sink tap",
"sewing box",
"shredder",
"basket with books",
"basketballs",
"cloth hangers",
"electrical device",
"box of food",
"liquid container",
"staircase wall",
"silicone gun",
"spray",
"bicycle helmets",
"camping chair",
"poles",
"baskets",
"notebooks",
"clothes on shelf",
"entrance arch",
"arcade",
"ceiling decorative lamp",
"framed text",
"ceiling ladder",
"exhibition table",
"ship model",
"whine shelf",
"table tennis table",
"terrace",
"bonsai tree",
"window seat",
"kitchen sink cabinet",
"lighter",
"fur carpet",
"bath side table",
"gravel",
"shower ceiling lamp",
"shower cosmetics",
"bowl of sweets",
"self-closing mechanism",
"projector screen",
"food stand",
"chest bench",
"shoulder bag",
"decorative window",
"bedroom table",
"drawer cabinet",
"decorative frame",
"box with photos",
"electric freshener",
"vinyl records",
"apple",
"card",
"ragdoll cat",
"pot lid",
"pouches",
"gun",
"handkerchiefs",
"training mat",
"painting roll",
"painting rolls",
"painting tray",
"glue",
"ruler",
"wrench",
"level",
"spatula",
"square",
"cans",
"base",
"rods",
"compound wall",
"recliner",
"chair stand",
"window valence",
"stack of jackets",
"potty",
"bottles of water",
"desk door",
"file binder",
"decorative mask",
"model",
"game console",
"changing table",
"instrument",
"canoe",
"pressure washer",
"oar",
"extractor",
"power cord",
"doorbell",
"traffic cone",
"entry phone",
"photo mounts",
"basketball hoop",
"goalpost",
"billiard cue",
"handcart",
"rolling pin",
"tapestry",
"skates",
"set of pictures",
"bath door",
"set of boxes",
"kitchen gloves",
"bed ladder",
"sheets",
"floor frame",
"grandfather clock",
"shoehorn",
"cake",
"cabinet parts",
"construction stuff",
"stroke",
"painting stuff",
"pencil case",
"bath shower",
"bath cosmetics",
"pillow seat",
"american flag",
"pen drive",
"soap tray",
"firewood bag",
"bottle of water",
"spice boxes",
"condensation furnace",
"drainage",
"child car seat",
"trimmer",
"drain",
"stole",
"big bag",
"decorative ceramic",
"pictures",
"bed for pet",
"cleaning powders/ liquids",
"cds",
"hi-hat",
"hi-hat stand",
"sheet music stand",
"bath hanger",
"buffet",
"kitchen ceiling",
"unknown"]






def build_obstacle_filter():
    # 1) 강제제외: 천장/부착물, 문/커튼/블라인드 등 (window 관련 제거됨 → 창은 포함 방향)
    exclude_patterns = [
        r'ceiling', r'chandelier',
        r'ceiling\s*(fan|lamp|light|fixture|rail|panel|molding|border|ladder|support|under|arch|dome|window|vent|duct|pipe|door)',

        r'\bdoor\b',
        r'sliding\s*door', r'garage\s*door', r'attic\s*door',
        r'doorway', r'door/window', r'door\s*window',
        r'door\s*(frame|post|handle|hinge|knob|stopper|screen|step)',
        r'\bgate\b',

        r'shutter', r'shade', r'blind',
        r'curtain(?!\s*wall)', r'curtain\s*(rod|rail|bar|box|hanger|valence)',
    ]

    # 2) 포함 힌트(고정·대형·중량) + window 포함
    include_hints = [
        # 구조물
        r'wall(?!\s*(clock|hanger|panel|board|soap|tv|toilet\s*paper))',
        r'wall\s*(panel|board|/outside|beam|cabinet)', r'compound\s*wall', r'paneling',
        r'pillar|column|parapet|arch',
        r'railing|banister|balustrade',
        r'stair(case)?|stair\s*step|stairs\s*railing|staircase',
        r'fence',
        r'chimney|hearth|mantel',
        r'partition',

        # 창(장애물 포함)
        r'\bwindow\b', r'window\s*glass', r'window\s*/outside', r'window\s*seat',

        # 대형 가구/수납
        r'\bbed\b|sofa|couch|armchair|bench|stool|rocking\s*chair|bean\s*bag\s*chair|beanbag',
        r'(\btable\b(?!\s*cloth))|\bdesk\b|coffee\s*table|dining\s*table|side\s*table|end\s*table',
        r'wardrobe|closet(?!\s*door)|dresser|chest(\s*of\s*drawers)?|nightstand|sideboard',
        r'bookshelf|shelving|\bshelf\b(?!\s*with)',   # "shelf with ..."은 후제외에서 걸러질 수 있음
        r'cabinet(?!\s*door)|cupboard|file\s*cabinet|bar\s*cabinet|storage\s*cabinet|wall\s*cabinet',
        r'locker|tv\s*stand|media\s*console|end\s*table',

        # 설비/가전/위생기기
        r'refrigerator|fridge|washing\s*machine|laundry\s*machine|dryer|dishwasher',
        r'oven(?!\s*and\s*stove)|stove|range\s*hood',
        r'boiler|furnace|heater|radiator|water\s*heater|air\s*conditioner',
        r'fireplace|sauna|jacuzzi',
        r'\bbath\s*tub\b|bathtub(?!\s*utensil)|\bbath\b(?!\s*(mat|towel|robe|hanger|shelf|utensil|dial|cosmetics|carpet|floor))',
        r'\btoilet\b(?!\s*(paper|brush|seat|cleaner|paper\s*dispenser))',
        r'washbasin|sink(?!\s*(pipe|tap|table|utensil))|vessel\s*sink|wash\s*cabinet|sink\s*cabinet|bathroom\s*cabinet',
        r'shower\s*(cabin|stall|cockpit|wall)(?!\s*(curtain|door|rod|bar|shelf))',

        # 카운터/작업대
        r'kitchen\s*counter|counter\s*top|countertop|worktop|kitchen\s*island|counter\s*desk',
    ]

    # 3) 소형/이동/잡동사니(후제외) — 필요시 확장
    small_loose_exclude = [
        r'window\s*(curtain|shade|shutter)',  # 창 커버류는 제외
        r'cup|mug|plate|bowl|flatware|cutlery|napkin|dinnerware|utensil',
        r'paper|magazine|newspaper|document|notes?|folder|file(?!\s*cabinet)|binders?|book(s)?(?!\s*(shelf|case|display))',
        r'cloth|towel|blanket|sheet(s)?|pillow(?!\s*seat)',
        r'bag|backpack|purse|wallet|handbag',
        r'candle(?!\s*holder|stand)|soap(?!\s*dispenser)|bottle(?!\s*dispenser)|jar|can(\s|$)|cosmetic(s)?',
        r'plant(?!\s*(ornament|stand|bed))|flower(?!\s*(pot|stand|bed))',
        r'toy(?!\s*box)|doll|stuffed\s*animal|plush',
        r'photo|picture|painting|poster|art(?!\s*frame)',
        r'laptop|keyboard(?!\s*piano)|mouse(?!\s*pad)|tablet|phone|remote\s*control|monitor(?!\s*stand?)',
        r'bin|trash\s*can|trash\s*bag|bucket|basket(?!\s*of\s*(towels|something|books|clothes))',
        r'frame(?!\s*|.*tv|.*display)|shampoo|soap\s*bottle|toilet\s*paper|paper\s*towel|detergent|cosmetics?',
        r'fan(?!\s*coil)|clock(?!\s*grandfather)',
        r'lamp(?!\s*stand|table)|light\s*fixture',
        r'mat(?!\s*h)', r'rug|carpet(?!\s*roll)',
        r'poster', r'calendar',
    ]

    # 4) 강제 포함(화이트리스트) — 패턴 누락 보완
    whitelist_exact = {
        'bookshelf', 'shelving', 'storage shelving', 'storage cabinet', 'sink cabinet',
        'kitchen island', 'kitchen counter', 'countertop', 'worktop',
        'tv stand', 'media console',
        'chest of drawers', 'dresser', 'wardrobe', 'closet shelving', 'closet storage area',
        'fireplace', 'furnace', 'boiler', 'radiator', 'water heater',
        'sauna', 'jacuzzi',
        'vessel sink', 'wash cabinet', 'bathroom cabinet',
        'shower cabin', 'shower stall', 'shower cockpit', 'shower wall',
        'compound wall', 'wall panel', 'paneling', 'wall board',
        'banister', 'balustrade', 'parapet', 'hearth', 'mantel',
        'locker', 'file cabinet', 'sideboard',
        'end table', 'side table', 'coffee table', 'dining table',
        'armchair', 'rocking chair', 'beanbag chair', 'bean bag chair',
        # 창 관련
        'window', 'window glass', 'window /outside', 'window seat',
    }

    # 5) 강제 제외(블랙리스트) — 소모품/소형이지만 패턴에 걸릴 수 있는 것
    blacklist_exact = {
        'toilet paper', 'soap', 'bottle', 'bottles', 'paper towel', 'paper towels',
        'plant', 'flower', 'poster', 'calendar', 'mat', 'rug', 'carpet',
        'monitor', 'laptop', 'mouse', 'phone',
        'window curtain', 'window shade', 'window shutter',
    }

    rx_ex = [re.compile(p, flags=re.I) for p in exclude_patterns]
    rx_in = [re.compile(p, flags=re.I) for p in include_hints]
    rx_sm = [re.compile(p, flags=re.I) for p in small_loose_exclude]

    def is_excluded(name: str) -> bool:
        s = name.lower().strip()
        if s in (x.lower() for x in blacklist_exact):
            return True
        return any(r.search(s) for r in rx_ex)

    def is_included(name: str) -> bool:
        s = name.lower().strip()
        if s in (x.lower() for x in whitelist_exact):
            return True
        return any(r.search(s) for r in rx_in)

    def is_small_loose(name: str) -> bool:
        s = name.lower().strip()
        return any(r.search(s) for r in rx_sm)

    def pick_obstacle_categories(categories: List[str]) -> List[str]:
        result = []
        for c in categories:
            if not c:
                continue
            s = c.strip()
            if not s or s.lower() == 'void':
                continue
            # 1) 강제제외
            if is_excluded(s):
                continue
            # 2) 포함힌트 충족 + 3) 소형/이동/잡동사니 후제외
            if is_included(s) and not is_small_loose(s):
                result.append(s)

        # 중복 제거(원래 순서 유지)
        seen = set()
        dedup = []
        for x in result:
            if x not in seen:
                seen.add(x)
                dedup.append(x)
        return dedup

    return pick_obstacle_categories