mp3d_room = [
    'bathroom',
    'bedroom',
    'closet',
    'dining room',
    'entryway/foyer/lobby',
    'familyroom',
    'garage',
    'hallway',
    'library',
    'laundryroom/mudroom',
    'kitchen',
    'living room',
    'meetingroom/conferenceroom',
    'lounge',
    'office',
    'porch/terrace/deck/driveway',
    'rec/game',
    'stairs',
    'toilet',
    'utilityroom/toolroom',
    'tv',
    'workout/gym/exercise',
    'outdoor areas containing grass, plants, bushes, trees, etc.',
    'balcony',
    'other room',
    'bar',
    'classroom',
    'dining booth',
    'spa/sauna',
    'junk',
    'no label',
]