replica_cat = [
    'void',
    'backpack',
    'base-cabinet',
    'basket',
    'bathtub',
    'beam',
    'beanbag',
    'bed',
    'bench',
    'bike',
    'bin',
    'blanket',
    'blinds',
    'book',
    'bottle',
    'box',
    'bowl',
    'camera',
    'cabinet',
    'candle',
    'chair',
    'chopping-board',
    'clock',
    'cloth',
    'clothing',
    'coaster',
    'comforter',
    'computer-keyboard',
    'cup', 
    'cushion', 
    'curtain',
    'ceiling',
    'cooktop',
    'countertop',
    'desk',
    'desk-organizer',
    'desktop-computer',
    'door',
    'exercise-ball',
    'faucet',
    'floor',
    'handbag',
    'hair-dryer', 
    'handrail',
    'indoor-plant',
    'knife-block',
    'kitchen-utensil',
    'lamp',
    'laptop',
    'major-appliance',
    'mat',
    'microwave',
    'monitor',
    'mouse',
    'nightstand',
    'pan',
    'panel',
    'paper-towel',
    'phone',
    'picture',
    'pillar',
    'pillow',
    'pipe',
    'plant-stand',
    'plate',
    'pot',
    'rack',
    'refrigerator',
    'remote-control', 
    'scarf',
    'sculpture',
    'shelf',
    'shoe',
    'shower-stall',
    'sink', 
    'small-appliance', 
    'sofa', 
    'stair', 
    'stool', 
    'switch', 
    'table', 
    'table-runner', 
    'tablet', 
    'tissue-paper', 
    'toilet', 
    'toothbrush', 
    'towel', 
    'tv-screen', 
    'tv-stand', 
    'umbrella', 
    'utensil-holder', 
    'vase', 
    'vent', 
    'wall', 
    'wall-cabinet', 
    'wall-plug', 
    'wardrobe', 
    'window', 
    'rug', 
    'logo', 
    'bag', 
    'set-of-clothing',
    'undefined'
    ]


cat2id = {
    'backpack': 1, 
    'base-cabinet': 2, 
    'basket': 3, 
    'bathtub': 4, 
    'beam': 5, 
    'beanbag': 6, 
    'bed': 7, 
    'bench': 8, 
    'bike': 9, 
    'bin': 10, 
    'blanket': 11, 
    'blinds': 12, 
    'book': 13, 
    'bottle': 14, 
    'box': 15, 
    'bowl': 16, 
    'camera': 17, 
    'cabinet': 18, 
    'candle': 19, 
    'chair': 20, 
    'chopping-board': 21, 
    'clock': 22, 
    'cloth': 23, 
    'clothing': 24, 
    'coaster': 25, 
    'comforter': 26, 
    'computer-keyboard': 27, 
    'cup': 28, 
    'cushion': 29, 
    'curtain': 30, 
    'ceiling': 31, 
    'cooktop': 32, 
    'countertop': 33, 
    'desk': 34, 
    'desk-organizer': 35, 
    'desktop-computer': 36, 
    'door': 37, 
    'exercise-ball': 38, 
    'faucet': 39, 
    'floor': 40, 
    'handbag': 41, 
    'hair-dryer': 42, 
    'handrail': 43, 
    'indoor-plant': 44, 
    'knife-block': 45, 
    'kitchen-utensil': 46, 
    'lamp': 47, 
    'laptop': 48, 
    'major-appliance': 49, 
    'mat': 50, 
    'microwave': 51, 
    'monitor': 52, 
    'mouse': 53, 
    'nightstand': 54, 
    'pan': 55, 
    'panel': 56, 
    'paper-towel': 57, 
    'phone': 58, 
    'picture': 59, 
    'pillar': 60, 
    'pillow': 61, 
    'pipe': 62, 
    'plant-stand': 63, 
    'plate': 64, 
    'pot': 65, 
    'rack': 66, 
    'refrigerator': 67, 
    'remote-control': 68, 
    'scarf': 69, 
    'sculpture': 70, 
    'shelf': 71, 
    'shoe': 72, 
    'shower-stall': 73, 
    'sink': 74, 
    'small-appliance': 75, 
    'sofa': 76, 
    'stair': 77, 
    'stool': 78, 
    'switch': 79, 
    'table': 80, 
    'table-runner': 81, 
    'tablet': 82, 
    'tissue-paper': 83, 
    'toilet': 84, 
    'toothbrush': 85, 
    'towel': 86, 
    'tv-screen': 87, 
    'tv-stand': 88, 
    'umbrella': 89, 
    'utensil-holder': 90, 
    'vase': 91, 
    'vent': 92, 
    'wall': 93, 
    'wall-cabinet': 94,
    'wall-plug': 95, 
    'wardrobe': 96, 
    'window': 97, 
    'rug': 98, 
    'logo': 99, 
    'bag': 100, 
    'set-of-clothing': 101, 
    'undefined': 0,#-1, 
    'other-leaf': 0,#-1, 
    'anonymize_picture': 0,#-1, 
    'anonymize_text': 0,#-1}
    }