data_paths:
  habitat_scene_dir: "nvme0n1/hong/VLMAPS/InstanceSeemMap/Data/simulation_dataset"
  vlmaps_data_dir: "nvme0n1/hong/VLMAPS/InstanceSeemMap/Data/habitat_sim/mp3d"

scene_names:
  - UwV83HsGsw3
data_cfg:
  rgb: true
  depth: true
  semantic: true
  resolution:
    w: 1080
    h: 720
  camera_height: 1.5