data_path: "/nvme0n1/hong/VLMAPS/InstanceSeemMap/Data"
data_type: "habitat_sim"
dataset_type : "mp3d" # "replica" 
vlm: "ours" # "lseg" "seem" "ours"
version: "dummy_d10c005" #"0115optimized2" #"b1209_ps50aft_s" # "lseg" "seem"
scene_ids:
  # - gTV8FGcVJC9_2
  - 2t7WUuJeko7_2
  # - 5LpN3gDmAk7_4
  # - apartment_0_1
  # - apartment_1_4
  # - apartment_2_2
  # - frl_apartment_1_1
  # - office_2_1
  # - office_3_1
  # - office_4_1
  # - room_0_1
  # - room_1_1
gt_version: "gt005" #005"
visualize: true
bool_save: false