data_path: "/home/vlmap_RCI/Data"
data_type: "habitat_sim"
dataset_type : "hm3dsem" # "replica" 
scene_id: 00861-GLAQ4DNUx5U #00824-Dd4bFSTQ8gi



targets:
  12:
    frame_id: 0
    instance_category: "chair"
    room_category: "living room"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
  11:
    frame_id: 0
    instance_category: "chair"
    room_category: "living room"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
  10:
    frame_id: 0
    instance_category: "chair"
    room_category: "living room"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
  9:
    frame_id: 0
    instance_category: "chair"
    room_category: "living room"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"