data_path: "/home/vlmap_RCI/Data"
data_type: "habitat_sim"
dataset_type : "hm3dsem" # "replica" 
scene_id: 00890-6s7QHgap2fW #00824-Dd4bFSTQ8gi



targets:
  176:
    frame_id: 882
    instance_category: "cabinet"
    room_category: " kitchen"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  105:
    frame_id: 253
    instance_category: "chair"
    room_category: "living room"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  35:
    frame_id: 380
    instance_category: "table"
    room_category: "living room"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  118:
    frame_id: 441
    instance_category: "curtain"
    room_category: "living room"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  418:
    frame_id: 1060
    instance_category: "sink"
    room_category: "kitchen"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  21:
    frame_id: 2047
    instance_category: "stairs"
    room_category: "entryway"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  229:
    frame_id: 1225
    instance_category: "toilet"
    room_category: "bathroom"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  357:
    frame_id: 393
    instance_category: "drawer"
    room_category: "living room"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  34:
    frame_id: 396
    instance_category: "tv"
    room_category: "living room"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  57:
    frame_id: 223
    instance_category: "stool"
    room_category: "living room"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  419:
    frame_id: 928
    instance_category: "faucet"
    room_category: "kitchen"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  188:
    frame_id: 903
    instance_category: "microwave"
    room_category: "kitchen"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  112:
    frame_id: 93
    instance_category: "sofa"
    room_category: "living room"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  417:
    frame_id: 868
    instance_category: "kitchen counter"
    room_category: "kitchen"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"
  228:
    frame_id: 1233
    instance_category: "toilet brush"
    room_category: "bathroom"
    query_type:
      - "object"
      - "room"
      - "caption"
      - "mixed"
      # - "abs"
      - "mixed_a"