data_path: "/home/vlmap_RCI/Data"
data_type: "habitat_sim"
dataset_type : "mp3d" # "replica" 
vlm: "ours" # "lseg" "seem" "ours"
version: "fin" #"b1209_ps50aft_s" # "lseg" "seem"
scene_id: 5LpN3gDmAk7_4

gt_version: "gt"
visualize:
  - "gt"
  - "obstacles"
  - "rgb"
  # - "map"
  # - "2Dmap"
  # - "instance"
  # - "instances_in_cat"
  # - "heatmap"
  # - "room"
instances_to_visualize: null # using for visualize_instance
categories_to_visualize: null #using for visualize_instances_in_cat
using_categorized_map: true
using_postprocessed_obstacles: true
heatmap_type: "simscore" # simscore / category
save_image: true